sudo: false
language: node_js
node_js:
  - "10"
cache:
  npm: false


services:
  - docker

stages:
  - build
  - build docker image
  - name: dockerhub dev deploy
    if: (branch = master) AND (NOT (type = pull_request))
  - name: github deploy
    if: tag IS present
  - name: dockerhub deploy
    if: tag IS present

jobs:
  include:
    - stage: build
      script: 
      - npm run eslint

    - stage: build docker image
      install: true
      script:
      - docker build -t dungeon-revealer .
      - docker run --rm dungeon-revealer echo "hello"

    - stage: dockerhub dev deploy
      install: true
      script:
      - echo "Deploying dev to Dockerhub..."
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t $DOCKER_USERNAME/dungeon-revealer:dev .
      - docker images
      - docker push $DOCKER_USERNAME/dungeon-revealer

    - stage: github deploy
      script:
        - echo "Deploying $TRAVIS_TAG to GitHub releases ..."
        - chmod +x bin/dungeon-revealer-linux bin/dungeon-revealer-macos
        - zip "dungeon-revealer-linux-$TRAVIS_TAG.zip" -j bin/dungeon-revealer-linux README.md
        - zip "dungeon-revealer-macos-$TRAVIS_TAG.zip" -j bin/dungeon-revealer-macos README.md
        - zip "dungeon-revealer-win-$TRAVIS_TAG.zip" -j bin/dungeon-revealer-win.exe README.md
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file:
          - "dungeon-revealer-linux-$TRAVIS_TAG.zip"
          - "dungeon-revealer-macos-$TRAVIS_TAG.zip"
          - "dungeon-revealer-win-$TRAVIS_TAG.zip"
        skip_cleanup: true
        draft: true
        on:
          tags: true

    - stage: dockerhub deploy
      install: true
      script:
      - echo "Deploying $TRAVIS_TAG, latest to Dockerhub..."
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t $DOCKER_USERNAME/dungeon-revealer:$TRAVIS_TAG -t $DOCKER_USERNAME/dungeon-revealer:latest .
      - docker images
      - docker push $DOCKER_USERNAME/dungeon-revealer


