name: Deploy wiki


on:
  push:
    paths:
      # Trigger only when wiki directory changes
      - 'wiki/**'
    branches:
      # And only on master branch
      - master

jobs:
  deploy-wiki:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Fetch merge commit and last commit from pull request
        fetch-depth: 2

    - name: Set environment
      run: |
        # Skip if HEAD is a merge commit
        if [[ $(git log -n 1 --pretty=format:%s) == "Merge Pull Request"* ]]; then
          echo "Skipping Merge commit"
          CMD='git log -n 1 --skip=1'
        else
          echo "Using current commit"
          CMD='git log -n 1'
        fi
        # Set the author name, author email, and message from the pull request
        echo "::set-env name=ACTION_MAIL::$(eval $CMD --pretty=format:%ae)"
        echo "::set-env name=ACTION_NAME::$(eval $CMD --pretty=format:%an)"
        echo "::set-env name=WIKI_PUSH_MESSAGE::$(eval $CMD --pretty=format:%s)"



    - name: Push Wiki Changes
      uses: docker://decathlon/wiki-page-creator-action:2.0.1@sha256:6cfea340b5003e7cc08d8cd413e295e90ac45e9f0e8dd86dec04b7aa8f58c3a4
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
        MD_FOLDER: wiki/
        OWNER: dungeon-revealer
        REPO_NAME: dungeon-revealer
